Validated use of defined_symbols.json with scan-callers

diff --git a/bin/c++-analyzer b/bin/c++-analyzer
--- a/bin/c++-analyzer
+++ b/bin/c++-analyzer
@@ -174,7 +174,7 @@ callers_analysis_options=`echo ${build_options} | sed -e s/-c\ //g | sed -e s/\\
 callers=`which callers++`
 
 # add some options when required
-callers_options="-std=c++11"
+callers_options="-std=c++11 -s /tmp/defined_symbols.json"
 
 # build the callers analysis command    
 analysis="${callers} ${callers_options} ${system_includes} ${callers_analysis_options}"
@@ -183,6 +183,13 @@ cd $path
 echo "launch callers analysis..."
 echo "${analysis}" | tee .tmp.last.callers.analysis.sh
 source .tmp.last.callers.analysis.sh
+if [ $? -ne 0 ]; then
+    echo "################################################################################"
+    echo "# Scan-Callers analysis error. Stop here !"
+    echo "################################################################################"
+    exit -1
+fi
+
 #exec "${analysis}"
 #exec "cd ${path} && ${analysis}"
 
